services:
    - type: web
      name: passport-bot
      env: node
      repo: https://github.com/chaiwattsw/line-bot-nodejs-on-render.git
      buildCommand: npm build
      startCommand: npm start
      plan: free
      autoDeploy: true
      envVars:
          - key: CHANNEL_ACCESS_TOKEN
            sync: true
          - key: CHANNEL_SECRET
            sync: true
          - key: SUPABASE_URL
            sync: true
          - key: SUPABSE_KEY
            sync: true
