services:
    - type: web
      name: passport-bot
      env: node
      repo: https://github.com/chaiwattsw/line-bot-nodejs-on-render.git
      buildCommand: npm install
      startCommand: node .
      plan: free
      autoDeploy: false
      envVars:
          - key: CHANNEL_ACCESS_TOKEN
            sync: false
          - key: CHANNEL_SECRET
            sync: false
